/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    ErrorMessage: typeof import('./components/common/ErrorMessage.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    OrderSettlement: typeof import('./components/common/OrderSettlement.vue')['default']
    OrderVerification: typeof import('./components/merchant/OrderVerification.vue')['default']
    PlaceholderImage: typeof import('./components/common/PlaceholderImage.vue')['default']
    ProductCard: typeof import('./components/customer/ProductCard.vue')['default']
    ProductList: typeof import('./components/customer/ProductList.vue')['default']
    QRScanner: typeof import('./components/merchant/QRScanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanButtonGroup: typeof import('vant/es')['ButtonGroup']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VersionSwitcher: typeof import('./components/common/VersionSwitcher.vue')['default']
  }
}
